name = "rvy/rodeo"
version = "0.1.0-rc.8"
description = "provides roblox studio's luau runtime via cli"
authors = ["rvy"]
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
  ".luaurc",
]

workspace_members = ["plugin"]

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"

[target]
environment = "lune"
bin = "build/release_bundle/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
argparse = { name = "caveful_games/argparse", version = "^0.1.2", target = "lune" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
chalk = { name = "kimpure/chalk_luau", version = "^0.1.8" }
