name = "rvy/rir3"
version = "0.0.4-rc.10"
description = "sync studio output to cli and also allow studio code execution from cli"
authors = ["rvy"]
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
  "plugins/**/*.luau",
  "plugins/**/*.json",
  ".luaurc",
]

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
stylua = { name = "pesde/stylua", version = "^2.3.0", target = "lune" }
selene = { name = "pesde/selene", version = "^0.29.0+toolchainlib.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[dependencies]
argparse = { name = "caveful_games/argparse", version = "^0.1.2", target = "lune" }
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
