name = "pesde/stylua"
version = "2.3.0"
description = "A Lua code formatter"
authors = ["CompeyDev <hi@devcomp.xyz>", "Johnny Morganz <johnnymorganz@outlook.com>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/stylua"
private = false
includes = ["init.luau", "README.md", "pesde.toml"]

[target]
environment = "lune"
bin = "init.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies.option]
name = "lukadev_0/option"
version = "^1.2.1"
index = "https://github.com/pesde-pkg/index"

[dependencies.result]
name = "lukadev_0/result"
version = "^1.2.1"
index = "https://github.com/pesde-pkg/index"

[dependencies.toolchainlib]
name = "pesde/toolchainlib"
version = "^0.2.0"
index = "https://github.com/pesde-pkg/index"
target = "lune"
